### ISSUE TITLE
SIM cards

### ISSUE THREAD

**Issue by JonnyTech** [l0stnam3/android_kernel_wileyfox_porridge#1]
Found ROM at http://4pda.ru/forum/index.php?showtopic=766693&st=0#entry58673773 and downloaded from https://www.androidfilehost.com/?fid=673368273298936939 (lineage-13.0-20170308-UNOFFICIAL-porridge.zip) this is the best LineageOS 13.0 ROM that I have used on my Spark+. But there is a problem where SIM cards are sometimes not detected when both slots are used.

Other ROM of LineageOS 14.1 at http://4pda.ru/forum/index.php?showtopic=766693&st=1680#entry59001466 (lineage-14.1-20170307-UNOFFICIAL-spark.zip) by mdeejay has no problems with SIM but other minor problems with system.

Is it possible to recompile with better SIM drivers from mdeejay or to update yours to 14.1?

**Comment by l0stnam3** [comment]
Try use it https://github.com/l0stnam3/android_frameworks_opt_telephony/commit/b63430781acd53197c912e714f5f903342d4b2e9

**Comment by JonnyTech** [comment]
Thank you for the quick reply. That commit was dated from February but the build that I am using is from March - is it not included? Can you provide instructions on how I can compile the files please.
